# these should all probably get resolved

# when we get on a modern version of chefstyle this can go away
Style/EndOfLine:
  EnforcedStyle: lf

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'lib/artifactory/resources/base.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/artifactory/resources/build_component.rb'
    - 'lib/artifactory/resources/repository.rb'
    - 'lib/artifactory/resources/user.rb'
    - 'spec/integration/resources/artifact_spec.rb'
