language: ruby
cache: bundler
dist: xenial
sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

bundler_args: --jobs 7

branches:
  only:
    - master

before_install:
  - gem install bundler

script: bundle exec rake travis:ci
