language: ruby
cache: bundler
dist: xenial
sudo: false

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6

bundler_args: --jobs 7

branches:
  only:
    - master

script: bundle exec rake travis:ci
